# Generated by Django 2.2.1 on 2019-06-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190604_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='accuracy',
            field=models.FloatField(default=0.5),
            preserve_default=False,
        ),
    ]
