# Generated by Django 2.2.1 on 2019-06-21 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_trial_accuracy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='hpjs_model',
        ),
        migrations.RemoveField(
            model_name='parametervalue',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='parametervalue',
            name='trial',
        ),
        migrations.RemoveField(
            model_name='trial',
            name='hpjs_model',
        ),
        migrations.DeleteModel(
            name='HPJS_Model',
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
        migrations.DeleteModel(
            name='ParameterValue',
        ),
        migrations.DeleteModel(
            name='Trial',
        ),
    ]
